### PR TITLE
feat: Add "unrank" btn and confirm dialog.

### PR DESCRIPTION
**Pull request by atomdmac**
# Goal of PR
Previously, clicking a ranked item would cause it to be removed from your list.  This made sense when we had separate ranked/unranked lists but now that we're relying on the auto-complete box as a means for exploring what candidates are on offer, this feature is confusing.

This PR adds an "eject" button that will unrank the item in question.  (I'm totally open to changing the icon if others think it's confusing and/or we can find something better).

## Pictures!
image
image

@SharpNotions/ten-hour-project

### CODE REVIEW

**Comment by tstodter** [comment]
Alternatives: 
- we could change the eject icon to "Unrank", and ditch the confirmation dialog. 
- Pop up a drop area at the bottom of the screen, so you can drag the unwanted ranking down and off your list.

**Comment by atomdmac** [comment]
@tstodter My goal for the moment is to make the "unrank" functionality more intuitive than it currently is.  (A number of people have commented that clicking on an item to remove it was pretty confusing).  I really like the "drag to unrank" option but in the interest of making the app more usable ASAP, I'd be inclined to track it as an `Issue:Improvement` and iterate on that later.  What do you think?

**Comment by ryanSN** [comment]
@atomdmac  I agree for the quick "fix" would be to do what you are doing, I think we don't need the dialog if the icon is the clickable item (like you have). If the row was still clickable like it is now, is the main issue. As you can miss click when dragging and lose it :( .

Any objection with changing out the icon to the remove icon?
```
 <v-icon dark left>remove_circle</v-icon>
```

I like the drag to bottom suggestion, but thats a bit of work 👍

**Comment by atomdmac** [comment]
@ryanSN The row is no longer clickable; just the `unrank`/`eject` button.  I'm happy to get rid of the confirmation dialog since it's easy to tear out and should be easy to re-add if we decide we need it later.

I initially went with the `eject` icon because when you unrank an item, it only deletes the ranking.  It seems like users could assume that a "remove" button deletes the item entirely. That said, it also occurs to me that `eject` has a good chance of not "reading" very well and a "remove" icon might work a lot better despite my initial hesitation.

Ultimately, the icon (or label, if we decide to go that route instead) is pretty easy to change so if we discover that it doesn't work well, an improvement is just a 5 minute PR away.

I say let's go with the `remove` icon and then iterate from there.

**Comment by ryanSN** [comment]
Maybe we should add alt text or title = `unrank from list` or `remove from list`, so there is a hover explaining what the icon does. 🤷‍♂️ 

Either way @atomdmac being the ⭐️ here with a quick fix.

**Comment by meganvbarton** [comment]
I like @ryanSN's idea of the alt text -- I prefer "unrank" over "remove".

**Comment by atomdmac** [comment]
How 'bout 'dis?
unrank

**Review by ryanSN — APPROVED** [review]
LGTM (ran locally)

**Pull request merged**
