### PR TITLE
Item Ranking UI

### PR DESCRIPTION
**Pull request by andynuge**
@SharpNotions/ten-hour-project

## Description
Added components for item ranking UI. I will try to get some tests written for it but I wanted to make sure we like this approach to ranking first.

## Trello Link
https://trello.com/c/VvpKcwUC/52-implement-user-ranking-ui

### CODE REVIEW

**Comment by payers1** [comment]
I think this also takes care of https://trello.com/c/BojL6nmy 👍

**Comment by andynuge** [comment]
It doesn't hit the api yet. I can squeeze that into this PR though.

**Review by atomdmac — APPROVED** [review]
LGTM.  Have you tested this on mobile by any chance?  Wondering if there are any additional considerations we'll need to make to get it working there.  In either case, I think this is good to go for now.

**Review by payers1 — APPROVED** [review]
🥇 LGTM with or without hitting the api part

**Comment by andynuge** [comment]
Seems to work ok in mobile. It probably needs some tweaks to the layouts so it uses more of the available room though.

**Pull request merged**
